name: 'Setup'
description: Setup project

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Install Yarn
      shell: bash
      run: npm install -g yarn

    - name: Install dependencies
      shell: bash
      run: yarn --immutable

    - name: Build
      shell: bash
      run: yarn build
